### ISSUE TITLE
API reference unusable in Mac OS Big Sur Chrome or Safari

### ISSUE THREAD

**Issue by joshgibs** [citrix/devdocs-issue-collector#17] opened 2021-02-26 19:11 UTC
The left-hand columns are unusable.  They flicker non-stop. This is a regression from previous website docs.

Mac OS 11.2.1
Safari 14.0.3
Chrome 88.0.4324.192

Docs URL:https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/?_ga=2.248779207.1375957459.1614365942-376611464.1614365942

**Comment by kurtcoll** [comment] 2021-02-26 21:06
@joshgibs - We're unable to reproduce this issue at the moment. I'm closing the ticket, but will keep an eye out for any other information about the issue.

**Closed as completed by kurtcoll** 2021-02-26 21:06 UTC
Labels: bug
